### ISSUE TITLE
Obstacle and random size

### ISSUE THREAD

**Issue by ckchen** [Shinao/Unity-GPU-Boids#3]
Hi Shinao,

I was wondering if this excellent project had some function like obstacles or instantiating the object using random size?
Thanks a lot.

**Comment by Shinao** [comment]
Obstacles could be generated through affectors (either pushing or pulling boids away).
I don't quite understand what objects you refer to next question, but that should be a matter of changing the scripts.

Though you might consider going for the ECS Unity Boids system route which gives you greater control over it instead of my GPU implementations.
